A fun minigame that we can create using python is a guessing game, where the user has to guess a secret number that is generated by the program. To create this game, we can use the random module to generate a random number between 1 and 10, and then prompt the user to guess the number. We can use a while loop to continue prompting the user for a guess until they get it right, and then print a congratulatory message. Here's what that might look like:


import random

# Generate a random number between 1 and 10
secret_num = random.randint(1, 10)

# Prompt the user to guess the number
guess = int(input("Guess the secret number (between 1 and 10): "))

# Use a while loop to continue prompting the user for a guess until they get it right
while guess != secret_num:
  print("Wrong, try again!")
  guess = int(input("Guess the secret number (between 1 and 10): "))

# If the user guesses the number correctly, print a congratulatory message
print("Congratulations, you guessed the secret number!")

If they guess the secret number correctly, they will receive a congratulatory message.
Otherwise, they will be prompted to guess again until they get it right.
This simple game can be extended in a number of ways, such as by adding more levels with different secret numbers to guess
 or by keeping track of the number of guesses it takes the user to get the right answer.
